import { IComment } from "../../types/comment";
import { Blog } from "../models/Blog";
import { Comment } from "../models/Comment";
import { getRandomInt } from "../utils/randomNumber"

const generateComments = (blogId: string): IComment[] => {
  const size = getRandomInt(20, 60);
  return Array(size)
    .fill(null)
    .map((_, index) => ({
      blogId,
      title: `World of Landies #${index}`,
      description:
        "A world of isometrical lands generated by a one of a kind algorithm with endless biome combinations. Spawning is completely random including the tiniest details to offer uniqueness to all!",
      user: "Tester"
    }));
}

export const initComments = async () => {
  console.log("Adding comments...");

  const blogIds = await (await Blog.find()).map((blog) => blog._id.valueOf());
  let totalList: IComment[] = [];
  for (const blogId of blogIds) {
    const blogComments = await generateComments(blogId);
    totalList = totalList.concat(blogComments)
  }

  await Comment.insertMany(totalList)
  console.log(`Added ${totalList.length} comments`);
}
